### ISSUE TITLE
Bad Character Fills

### ISSUE THREAD

**Issue by brombomb** [marumari/cryptnomicon#2]
Was perusing the images here https://marumari.github.io/cryptonom-icon and found a few of them have bad fills (looks like the wrong font).

Examples:
key-private-invalid
key-private-private (worst)
key-public-alice (only slightly)
key-public-bob (only slightly)
key-public-ca (only slightly)
key-public-intermediate
key-public-root

**Comment by april** [comment]
I only see the problem on key-private-private, and I've tried a bunch of different things to fix it.  I'll open up a bug with Affinity and see if they have any ideas.  Thanks for opening the bug!

**Comment by april** [comment]
I will add that a lot of bugs seem platform specific, with Linux having the most rendering issues.  Can I ask your platform?

**Comment by brombomb** [comment]
Windows 10 - Chrome Version 55.0.2883.87 I had my browser open at 1280 x 1080

**Comment by stof** [comment]
On Linux, I have rendering issues on almost all icons using text. See these screenshots:
![cryptonom_text](https://cloud.githubusercontent.com/assets/439401/21419319/33832826-c827-11e6-97f1-cb721e0b987e.png)
![cryptonom_certificate](https://cloud.githubusercontent.com/assets/439401/21419321/3968492e-c827-11e6-9073-4f4fdcf109df.png)

The SVG code looks weird as the end of words is in separate tspans.
and the font families used for text seems to include fonts not available on Linux by default, which means it uses a default font instead, which may have a different size (not compatible with the position of these tspans or with the width of the text in the icon)

**Comment by april** [comment]
Hmm, I just use bog standard Helvetica for each of my SVGs, but when I looked through the statistics, it seems that there is essentially no font that appears on all three major systems consistently.

I'll go ahead and re-export all the SVGs, with the fonts being exported as curves.  The downside is that it will make the SVGs have a considerably larger file size.

**Comment by april** [comment]
I've done this and checked all of the SVG files from my Ubuntu 14 machine and everything seems to be working well now.  I'm going to close this, but let me know if you're still seeing issues on any of the exports and I can go ahead and reopen it.

Thank you so very much for reporting this!
